# Generated by Django 4.0.6 on 2022-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreadsid', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=128)),
                ('authorLF', models.CharField(blank=True, max_length=156)),
                ('authorFL', models.CharField(blank=True, max_length=156)),
                ('ISBN', models.CharField(blank=True, max_length=50)),
                ('ISBN13', models.CharField(blank=True, max_length=50)),
                ('myRating', models.IntegerField(blank=True)),
                ('avgRating', models.IntegerField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=50)),
                ('pages', models.IntegerField(blank=True)),
                ('published', models.IntegerField(blank=True)),
                ('firstpublished', models.IntegerField(blank=True)),
                ('dateRead', models.CharField(blank=True, max_length=50)),
                ('dateAdded', models.CharField(blank=True, max_length=50)),
                ('readStatus', models.CharField(blank=True, max_length=50)),
                ('readCount', models.IntegerField(blank=True)),
            ],
        ),
    ]
