# Generated by Django 4.0.6 on 2022-10-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='goodreadsid',
        ),
        migrations.AddField(
            model_name='books',
            name='goodreadsID',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN13',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='authorFL',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='authorLF',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='avgRating',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateAdded',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateRead',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='myRating',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='readStatus',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
