# Generated by Django 4.0.6 on 2022-10-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_goodreadsid_books_goodreadsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
