# Generated by Django 4.0.6 on 2022-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='firstpublished',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='published',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='readCount',
            field=models.IntegerField(null=True),
        ),
    ]
