# Generated by Django 4.0.6 on 2022-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_firstpublished_alter_books_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='firstpublished',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='published',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
    ]
