# Generated by Django 4.0.6 on 2022-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_firstpublished_alter_books_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookShelves',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
