# Generated by Django 4.0.6 on 2022-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_bookshelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='avgRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
