# Generated by Django 4.0.6 on 2022-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_avgrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN13',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='goodreadsID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='myRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='readCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
