# Generated by Django 4.0.6 on 2022-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_books_isbn_alter_books_isbn13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
    ]
