# Generated by Django 4.0.6 on 2022-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN13',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
    ]
