# Generated by Django 4.0.6 on 2022-10-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN13',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
