# Generated by Django 4.0.6 on 2022-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='dateAdded',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateRead',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
