# Generated by Django 4.0.6 on 2022-10-25 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_books_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='dateAdded',
            field=models.DateField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateRead',
            field=models.DateField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(default=None, verbose_name=datetime.datetime(2022, 10, 25, 20, 16, 50, 750371)),
        ),
    ]
