# Generated by Django 4.0.6 on 2022-10-25 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_books_dateadded_alter_books_dateread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(default=None, null=True, verbose_name=datetime.datetime(2022, 10, 25, 20, 20, 24, 102817)),
        ),
    ]
